final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestTemplate = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestReportEngineSettings = ReportEngineSettings();
requestReportEngineSettings.dataSourceType = ReportEngineSettings_DataSourceTypeEnum.json;
requestReportEngineSettings.dataSourceName = 'persons';
final buildReportRequest = BuildReportOnlineRequest(requestTemplate, 'Data.json', requestReportEngineSettings);
await wordsApi.buildReportOnline(buildReportRequest);