final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('compareTestDoc1.doc').readAsBytes()).buffer.asByteData();
final requestCompareData = CompareData();
requestCompareData.author = 'author';
requestCompareData.comparingWithDocument = 'TestCompareDocument2.doc';
requestCompareData.dateTime = DateTime(2015, 10, 26, 0, 0, 0);
final requestComparingDocument = (await File('compareTestDoc2.doc').readAsBytes()).buffer.asByteData();
final compareRequest = CompareDocumentOnlineRequest(requestDocument, requestCompareData, comparingDocument: requestComparingDocument, destFileName: '/TestCompareDocumentOut.doc');
await wordsApi.compareDocumentOnline(compareRequest);