final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestWatermarkText = WatermarkText();
requestWatermarkText.text = 'This is the text';
requestWatermarkText.rotationAngle = 90;
final insertRequest = InsertWatermarkTextOnlineRequest(requestDocument, requestWatermarkText);
await wordsApi.insertWatermarkTextOnline(insertRequest);