final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestStyleInsert = StyleInsert();
requestStyleInsert.styleName = 'My Style';
requestStyleInsert.styleType = StyleInsert_StyleTypeEnum.paragraph;
final insertRequest = InsertStyleOnlineRequest(requestDocument, requestStyleInsert);
await wordsApi.insertStyleOnline(insertRequest);