final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocumentData = (await File("Sample.docx").readAsBytes()).buffer.asByteData();
final requestCustomXmlPart = CustomXmlPartInsert();
requestCustomXmlPart.id = 'hello';
requestCustomXmlPart.data = '<data>Hello world</data>';
final insertRequest = InsertCustomXmlPartOnlineRequest(requestDocumentData, requestCustomXmlPart);
await wordsApi.insertCustomXmlPartOnline(insertRequest);