final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocumentData = (await File("Sample.docx").readAsBytes()).buffer.asByteData();
final requestTable = TableInsert();
requestTable.columnsCount = 5;
requestTable.rowsCount = 4;
final insertRequest = InsertTableOnlineRequest(requestDocumentData, requestTable, nodePath: '');
await wordsApi.insertTableOnline(insertRequest);