final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestTabStopInsertDto = TabStopInsert();
requestTabStopInsertDto.alignment = TabStopBase_AlignmentEnum.left;
requestTabStopInsertDto.leader = TabStopBase_LeaderEnum.none;
requestTabStopInsertDto.position = 72;
final insertRequest = InsertOrUpdateParagraphTabStopOnlineRequest(requestDocument, requestTabStopInsertDto, 0);
await wordsApi.insertOrUpdateParagraphTabStopOnline(insertRequest);