final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDrawingObject = DrawingObjectInsert();
requestDrawingObject.height = 0;
requestDrawingObject.left = 0;
requestDrawingObject.top = 0;
requestDrawingObject.width = 0;
requestDrawingObject.relativeHorizontalPosition = DrawingObjectInsert_RelativeHorizontalPositionEnum.margin;
requestDrawingObject.relativeVerticalPosition = DrawingObjectInsert_RelativeVerticalPositionEnum.margin;
requestDrawingObject.wrapType = DrawingObjectInsert_WrapTypeEnum.inline;
final requestImageFile = (await File('Common/aspose-cloud.png').readAsBytes()).buffer.asByteData();
final insertRequest = InsertDrawingObjectRequest('Sample.docx', requestDrawingObject, requestImageFile);
await wordsApi.insertDrawingObject(insertRequest);