final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestReplaceText = ReplaceTextParameters();
requestReplaceText.oldValue = 'aspose';
requestReplaceText.newValue = 'aspose new';
final replaceRequest = ReplaceTextOnlineRequest(requestDocument, requestReplaceText);
await wordsApi.replaceTextOnline(replaceRequest);