final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Common/test_multi_pages.docx').readAsBytes()).buffer.asByteData();
final requestSaveOptionsData = SaveOptionsData();
requestSaveOptionsData.saveFormat = 'pdf';
requestSaveOptionsData.fileName = '/TestSaveAs.pdf';
final saveRequest = SaveAsOnlineRequest(requestDocument, requestSaveOptionsData);
await wordsApi.saveAsOnline(saveRequest);