final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Common/test_multi_pages.docx').readAsBytes()).buffer.asByteData();
final requestSaveOptions = TiffSaveOptionsData();
requestSaveOptions.saveFormat = 'tiff';
requestSaveOptions.fileName = '/abc.tiff';
final saveRequest = SaveAsTiffOnlineRequest(requestDocument, requestSaveOptions);
await wordsApi.saveAsTiffOnline(saveRequest);