final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocumentData = (await File("/FormFilled.docx").readAsBytes()).buffer.asByteData();
final requestFormField = FormFieldTextInput();
requestFormField.name = 'FullName';
requestFormField.enabled = true;
requestFormField.calculateOnExit = true;
requestFormField.statusText = '';
requestFormField.textInputType = FormFieldTextInput_TextInputTypeEnum.regular;
requestFormField.textInputDefault = 'No name';
final updateRequest = UpdateFormFieldOnlineRequest(requestDocumentData, requestFormField, 0, nodePath: 'sections/0');
await wordsApi.updateFormFieldOnline(updateRequest);