final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestDrawingObject = DrawingObjectUpdate();
requestDrawingObject.left = 0;
final requestImageFile = (await File('Common/aspose-cloud.png').readAsBytes()).buffer.asByteData();
final updateRequest = UpdateDrawingObjectOnlineRequest(requestDocument, requestDrawingObject, requestImageFile, 0);
await wordsApi.updateDrawingObjectOnline(updateRequest);