final clientId = "####-####-####-####-####";
final clientSecret = "##################";
final config = Configuration(clientId, clientSecret);
final wordsApi = WordsApi(config);
final requestDocument = (await File('Sample.docx').readAsBytes()).buffer.asByteData();
final requestFormat = TableRowFormat();
requestFormat.allowBreakAcrossPages = true;
requestFormat.headingFormat = true;
requestFormat.height = 10;
requestFormat.heightRule = TableRowFormat_HeightRuleEnum.auto;
final updateRequest = UpdateTableRowFormatOnlineRequest(requestDocument, 'sections/0/tables/2', requestFormat, 0);
await wordsApi.updateTableRowFormatOnline(updateRequest);